version: "3.7"

services:
  proxy:
    image: traefik:v2.2
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"

  application:
    image: application:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000
    environment:
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.backend=application"
      - "traefik.http.routers.application.rule=Host(`application.localhost`)"
