version: "3.7"

services:
  proxy:
    image: traefik:v2.2
    ports:
      - 4000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"

  server:
    image: server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000
    environment:
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.backend=server"
      - "traefik.http.routers.server.rule=Host(`localhost`)"
